server:
  port: 8081
  servlet:
    port: 8081
    contextPath: /api

spring:

  application:
    name: FoodOrderingApp-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  logging:
      level:
          org.hibernate.SQL: DEBUG
          org.hibernate.type: TRACE

